### ISSUE TITLE
the error i encountered

### ISSUE THREAD

**Issue by hitymsun** [turian/textSNE#1]
when i ran this toolkit on the linux platform, i encountered the following error. 

Platform detected : linux2
Calling executable "/home/ymsun/textSNE-master/tSNE_linux"
sh: 1: /home/ymsun/textSNE-master/tSNE_linux: Permission denied
Reading result.dat
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    out = tsne(x, no_dims=2, perplexity=30, initial_dims=30)
  File "/home/ymsun/textSNE-master/calc_tsne.py", line 21, in tsne
    Xmat,LM,costs=readResult()
  File "/home/ymsun/textSNE-master/calc_tsne.py", line 85, in readResult
    f=open('result.dat','rb')
IOError: [Errno 2] No such file or directory: 'result.dat'

**Comment by turian** [comment]
Do you have that executable in that location? Did you make sure it is chmod'ed to be executable?
